### ISSUE TITLE
Unable to locate package cronic

### ISSUE THREAD

**Issue by Facer66** [openspace42/raptor#1]
your installer used on debian 8 ends with: Unable to locate package cronic

**Comment by nikksno** [comment]
Good point, haven't tested on debian lately, cronic doesn't seem to be available from the main repo on debian 8, only 9 and later. Since it's just a shell script, it's a quick fix, i'll look into this tomorrow. Thanks for the report!

**Comment by Facer66** [comment]
In Debian 8 it is included in the package: --moreutils

**Comment by nikksno** [comment]
Thanks for the tip, to be on the safe side for other distros I've just curled it from the dev's website. Please remove the existing raptor directory, re-clone, and re-install with `bash raptor/setup -be`
The `-b` argument will use the bleeding-edge bash-functions which underly the project, and the `-e` argument will use bleeding-edge raptor therefore not requiring cronic to be installed via apt. Let me know if this works for you. Thanks!

**Comment by Facer66** [comment]
Yes the install ran without any issue. All running!

**Comment by nikksno** [comment]
Awesome thanks
