### ISSUE TITLE
restore_type: unbound variable

### ISSUE THREAD

**Issue by HesselTjeerdsma** [openspace42/raptor#10]
When I try to restore from a local backup I get to following error:

/root/openspace42/bash-functions/functions/backup_restore: line 905: restore_type: unbound variable

**Comment by nikksno** [comment]
@HesselTjeerdsma could you paste here a full log, from the command invocation onwards?
Thanks

**Comment by HesselTjeerdsma** [comment]
**I am using a backup file from another machine, which I copied to the openspace42/raptor/backup/archive directory.**
**When I try to install it without the -i flag I get:**
`root@server1:~# bash openspace42/raptor/tools/raptor-restore
Starting raptor-restore script on 2018-04-09_00-00-32...
openspace42/raptor/tools/raptor-restore: line 195: install_easyengine: command not found`

**With the -i flag:**
`root@server1:~# bash openspace42/raptor/tools/raptor-restore -i
Starting raptor-restore script on 2018-04-09_00-02-45...
Not [re-]installing EasyEngine as per | -i |...
openspace42/raptor/tools/raptor-restore: line 217: syntax error near unexpected token }`

**Then I tried removing the following function on line 217 of the raptor-restore file:**
`restore_from_standalone_content_validation() {
        ### Perform standalone restore content validations 
}
`
**Doing so I could start the restoring process:**
root@server1:~# bash openspace42/raptor/tools/raptor-restore -i
Starting raptor-restore script on 2018-04-09_00-09-44...
Not [re-]installing EasyEngine as per | -i |...
Is the backup you're trying to restore stored locally on this machine [i.e. you're trying to restore a previous state of this running instance of raptor] or is it stored elsewhere [i.e. you're changing machine or your previous machine's data was wiped or lost]? 
1) backup file stored locally	 3) exit
2) backup file stored elsewhere
#? 1
These are the backup dates available for restore:
ee-br-backup-2018-04-08_04-08-02
[press enter to continue...]
Now choose the file you'd like to restore: 
1) ./ee-br-backup-2018-04-08_04-08-02.tar.bz2
2) exit
#? 1
Backup file ./ee-br-backup-2018-04-08_04-08-02.tar.bz2 selected.
Is this the correct file? (Y[es]/n[o]/e[xit]) y
ee-br-backup-2018-04-08_04-08-02/

**A lot of lines showing the web-files and web-directories are displayed and after this:**
`/root/openspace42/bash-functions/functions/backup_restore: line 905: restore_type: unbound variable`

**Comment by nikksno** [comment]
Ok, I was testing it myself and already fixed the first two errors. Working on the last one. Stay tuned. Thank you.

**Comment by nikksno** [comment]
@HesselTjeerdsma ok the latest commit should have fixed that. It was an error introduced about a month back when I wrote the code for "boostrap mode" which allows you to run a restore on a fresh machine where raptor insn't installed yet to *first* recover your settings and stuff and only *then* actually running the installer. The loop closing logic was incorrect on one line and that broke the rest of the script. Let me know if it works for you now! Thanks!

**Comment by HesselTjeerdsma** [comment]
@nikksno Thanks for your quick reply! I still run into to the same problems with -i flag. Also, I am using the backup files from your previous backup utility. Now the error I get is: 
`rsync: change_dir "/root/openspace42/raptor/backups/restores/local/ee-br-backup-2018-04-08_04-08-02/conf" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1183) [sender=3.1.1]`
When I extract the backup files I don't see a conf dir.
Tomorrow I will try to restore on a clean install, maybe that will help.

**Comment by nikksno** [comment]
@HesselTjeerdsma could you:
`ls /root/openspace42/raptor/backups/restores/local/`
`ls /root/openspace42/raptor/backups/restores/local/ee-br-backup-2018-04-08_04-08-02/`
and if necessary any subdir you find in there?

Thanks

**Comment by HesselTjeerdsma** [comment]
Hi, here you go:

```
root@server1:~# ls /root/openspace42/raptor/backups/restores/local/
ee-br-backup-2018-04-08_04-08-02  raptor-backup-2018-04-09_15-27-14
root@server1:~# ls /root/openspace42/raptor/backups/restores/local/ee-br-backup-2018-04-08_04-08-02/
firefly.htfix.nl  htfix.nl        maisonlomont.nl  oud.maisonlomont.nl  zlef.nl
hindrikje.nl      lysandlimes.nl  maisonlomont.tk  stemwijzernu.nl
```
**every subdir consists of:**
```
root@server1:~# ls /root/openspace42/raptor/backups/restores/local/ee-br-backup-2018-04-08_04-08-02/lysandlimes.nl/
htdocs  mysqldump.sql  wp-config.php
```

**Comment by nikksno** [comment]
Ahh ok I see, you have an old version of the backup that doesn't have the subdivision in /conf and /data. Run this as root to fix it:

```
cd /root/openspace42/raptor/backups/restores/local/ee-br-backup-2018-04-08_04-08-02/
mkdir data
mv !(data) data
cp -r openspace42/raptor/conf/ conf
```

And this to check:

```ls *.*```

Sorry but since we're so early in developement and virtually no-one is using our project yet, it's hard to keep backwards compatibility, but the backed up data will always be valid. I'll publish this into the wiki if it works for you.

**Comment by HesselTjeerdsma** [comment]
Yes, this worked for me. Thanks a lot! If I could give another suggestion, it would be really nice to have all new accounts + passwords in a file after restoring all sites. But next to that thanks for making this tool!

**Comment by nikksno** [comment]
Are you talking about the wordpress sites admin user/password?

**Comment by nikksno** [comment]
The wp credentials are the same as your previous installation as all of the user information is preserved, regardless of what EE prints out during site creation, as we then re-import all db tables including the user and user-meta ones. Your existing log in info will work exactly as before.
