### ISSUE TITLE
Backup Compression

### ISSUE THREAD

**Issue by xiano8494** [openspace42/raptor#11]
I'm not sure if this is possible, but I wonder whether there should be an option to not compress the backups?
For some people, I suspect this is not an issue, but my backup is going to take 6 hours to compress and is beating up the CPU pretty badly. I suspect the compression ratio won't be huge either as the majority of the files are already compressed anyway. Obviously, the database backups will be compressed massively, but they only make up a tiny proportion of my overall backup.
Thoughts?

**Comment by xiano8494** [comment]
Further to this, if we "must" compress the backups, I will need some way to restrict the CPU usage of the process, currently the CPU is getting so battered that website performance is suffering. (I appreciate that normally backups will run overnight, but this should still be a consideration)

**Comment by nikksno** [comment]
Test a reinstall now with beta enabled, you should be allowed to set your compression type [bz2/none]. Let me know!

**Comment by xiano8494** [comment]
Now testing this

**Comment by xiano8494** [comment]
Perfect, a much more acceptable 24 mins to archive the backup (Although you might want to change the word "compressing")

Now compressing backup...

47.8GiB 0:24:36 [33.1MiB/s] [==============================================================================================>] 101%            

Finished compressing backup and stored in | /var/backups/archive/ |

**Comment by nikksno** [comment]
Perfect. I've changed it to "archiving". Closing for now.
