### ISSUE TITLE
Testing restore from S3 failed

### ISSUE THREAD

**Issue by xiano8494** [openspace42/raptor#12]
After it **finally** finished compressing my backup, the next section failed.
I wonder if it may be to do with the double slashes? Also, "/var/backups//temp/duplicity-log" didn't exist, with or without the double slash.
I did not change my encryption password.

"
Finished compressing backup and stored in | /var/backups//archive/ | 

Finished local backup.

Now testing restore from S3 to /var/backups//restores/s3/ to ensure existing backups integrity and passphrase match...

This is going to take some time. Please let the process run, it won't print any output until its done.

Testing restore from S3 failed.

This is likely due to an incorrect passphrase [check | /var/backups//temp/duplicity-log | for messages like: | gpg: decryption failed: bad key |].

If this is the case, you've likely changed your backups encryption passphrase on this machine between your last backup and this one.
"

**Comment by nikksno** [comment]
Try clearing your S3 storage entirely [from your S3 console move everything into a subdir called "old" or something] and try again please, let me know!

**Comment by xiano8494** [comment]
Nothing in my S3 bucket at all.

**Comment by nikksno** [comment]
Also does your "/var/backups//temp/" folder exist? "/var/backups//temp/duplicity-log" should exist before the script exits, try and read it while the script is running.

**Comment by xiano8494** [comment]
/var/backups/temp exists and contains "raptor-backup-2018-04-10_04-08-01"
The only problem is the script takes 6 hours to zip the backup ( Hence #11 ) so manually monitoring the duplicity log is going to be a challenge!

**Comment by nikksno** [comment]
Ok, I'm working on https://github.com/openspace42/raptor/issues/11 so let's get that figured out first and then we'll takle this one.

**Comment by xiano8494** [comment]
OK, it completed (and failed) before I had a chance to check the log, so I'm now running again. However, I have a few other observations.

Firstly, when I reinstalled, I removed the trailing slash from my backup location. While that removed the extra slash in the messages, it didn't help the backup process to complete.

Secondly, the message mentions "Edit the file | /root/openspace42/raptor/config", but that location isn't valid. It should be something like ~/openspace42/raptor/conf/backups/s3/backups_passphrase

And lastly, why are we deleting the log after the process fails! We should definitely not do that!

**Comment by nikksno** [comment]
The trailing slash should definitely not be an issue, I've been using it both with and without in the last few days just to be sure and can confirm it hasn't caused any issues either way, otherwise we'd be removing the slash programmatically after the prompt.

That's true, it's the old location, just changed the message.

As for the temp dir getting erased, that should only happen on successful restore. Can you output the entire log from the script?

Thanks

**Comment by xiano8494** [comment]
This time there was a duplicity log, contents below:

Traceback (innermost last):
  File "/usr/bin/duplicity", line 1555, in <module>
    with_tempdir(main)
  File "/usr/bin/duplicity", line 1541, in with_tempdir
    fn()
  File "/usr/bin/duplicity", line 1380, in main
    action = commandline.ProcessCommandLine(sys.argv[1:])
  File "/usr/lib/python2.7/dist-packages/duplicity/commandline.py", line 1135, in ProcessCommandLine
    backup, local_pathname = set_backend(args[0], args[1])
  File "/usr/lib/python2.7/dist-packages/duplicity/commandline.py", line 1010, in set_backend
    globals.backend = backend.get_backend(bend)
  File "/usr/lib/python2.7/dist-packages/duplicity/backend.py", line 223, in get_backend
    obj = get_backend_object(url_string)
  File "/usr/lib/python2.7/dist-packages/duplicity/backend.py", line 209, in get_backend_object
    return factory(pu)
  File "/usr/lib/python2.7/dist-packages/duplicity/backends/_boto_single.py", line 166, in __init__
    self.resetConnection()
  File "/usr/lib/python2.7/dist-packages/duplicity/backends/_boto_single.py", line 191, in resetConnection
    location=self.my_location)
  File "/usr/lib/python2.7/dist-packages/boto/s3/connection.py", line 621, in create_bucket
    response.status, response.reason, body)
 S3ResponseError: S3ResponseError: 400 Bad Request
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InvalidRequest</Code><Message>The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.</Message>

**Comment by nikksno** [comment]
Awesome. Do you feel like sharing the credentials or creating a similar bucket on the same endpoint so I can do some testing?

**Comment by xiano8494** [comment]
I believe I can add permission for you to access the bucket in question if you shared your AWS account name?
The bucket is in the EU London region.

I have found this: https://superuser.com/questions/1202608/duplicity-and-s3-frankfurt-bucket-error-please-use-aws4-hmac-sha256?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa which appears to reference a similar issue.  I wonder if it is related?

**Comment by xiano8494** [comment]
My endpoint is set as: s3.eu-west-2.amazonaws.com

**Comment by xiano8494** [comment]
I will need to look at your access request, I don't know a huge amount about AWS, so I'll need to understand what you're asking before going ahead.

**Comment by nikksno** [comment]
No problem, simply go here: https://console.aws.amazon.com/iam/home#/users, add a user and select "programmatic access" when doing so, skip adding permissions, only attach this inline policy:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:ListBucket"
            ],
            "Resource": [
                "arn:aws:s3:::BUCKETNAMEHERE"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:PutObject",
                "s3:GetObject"
            ],
            "Resource": [
                "arn:aws:s3:::BUCKETNAMEHERE/*"
            ]
        }
    ]
}

And only substitute BUCKETNAMEHERE with your actual bucket name. Then get the keys for that user [Access Key ID and Secret Access Key] and send them to me if you'd lile. This is how you should *always* use S3, with single-bucket policies, to minimize damages in case one of your servers gets hacked.

**Comment by xiano8494** [comment]
Done

**Comment by nikksno** [comment]
Ok, thanks to @xiano8494 and the amazing project mailinabox [which we at openspace also use for our mailserver] and their commit https://github.com/mail-in-a-box/mailinabox/commit/5e4c0ed825c0e4d2299f0ead5c5c3bc4c11d4226, I figured this out. Ubuntu 16 has an old package for python-boto, so now we install it via pip instead of apt-get, and that upgrades boto to the latest version so that now duplicity can auto-detect the signature version required on the S3 endpoint and auto-select the correct one to use, therefore lifting us from needing to have the user set wether or not to set `export S3_USE_SIGV4="True”` as an install-time option. @HesselTjeerdsma can I kindly ask you if you could do a `-be` reinstall and let me know if everything works for you S3-wise? Thanks!

**Comment by HesselTjeerdsma** [comment]
@nikksno I just did a reinstall, and everything is working as it should!

**Comment by nikksno** [comment]
Awesome thank you guys
