### ISSUE TITLE
Backup script doesn't exit on failure

### ISSUE THREAD

**Issue by xiano8494** [openspace42/raptor#13]
I had to manually kill the backup script after it said it was exiting after failing due to a shortage of space.

:~# bash openspace42/raptor/tools/raptor-backup

Starting raptor-backup script on 2018-04-11_12-55-56...

You have 1 local backups occupying 53017 MB of space.

Estimated backup size [148188 MB] LARGER than available disk space [138618 MB].

Now purging old backups while respecting your specified number of minimum backups to keep...

root@shost7:~# The specified number of minimum backups to keep [1] is too high to free enough disk space for the next backup.

Lower this figure by re-running the install and lowering this figure during configuration or make more space available on this machine.

Exiting...

^C

**Comment by nikksno** [comment]
It's an issue I've been having at times. Not sure why since the code is:

```
echo "${r}${b}Exiting...${x}"
echo
exit 1
```

I'll leave the issue open but have no idea as how to solve it for now, and won't be looking into it before all other issues are closed. If you have any ideas please let me know. Thanks!

**Comment by nikksno** [comment]
I've added a `sleep 1` which should help. Let's gather some usage data with this edit and see what happens.

**Comment by nikksno** [comment]
Ok, good, closing for now.
