### ISSUE TITLE
Cannot connect to digitalocean object storage

### ISSUE THREAD

**Issue by HesselTjeerdsma** [openspace42/raptor#15]
Hello,

I tried adding my digitalocean space (a s3 compatible object-storage service) to the raptor backup tool, but I got the following error: S3 connection details do NOT appear to be valid. Could you please help fix this? If necessary, I can provide you the keys for testing.

**Comment by HesselTjeerdsma** [comment]
I see that "https://$bucket.s3.amazonaws.com$aws_path$file" is hardcoded in the putS3 function in the backup_restore code, maybe change that to "https://$bucket.$endpoint$aws_path$file"?

**Comment by HesselTjeerdsma** [comment]
The error is in line 187 of the setup_backup_resotre bash function. `s3cmd --configure --access_key="$s3_access_key_id" --secret_key="$s3_secret_access_key" --host="$s3_endpoint" -s --no-encrypt"`
**This can be fixed by adding:**
`--host-bucket="%(bucket).$s3_endpoint"`

**Comment by nikksno** [comment]
You're right about the two hardcoded `s3.amazonaws.com` in the putS3, but this actually only controls the monthly uploads function. As for duplicity, why is it that we need the extra option if we're already including `--host="$s3_endpoint"` ? Is this for compatibility purposes with non-Amazon S3 endpoints?

In any event, I've added it, and my Amazon S3 connection still checks out as working, I've also fixed the putS3 function, let me know if the setup works for you! Thanks!

**Comment by nikksno** [comment]
@xiano8494 next time you happen to re-install would you mind checking your S3 connection shows as good during install? Thank you!

**Comment by HesselTjeerdsma** [comment]
@nikksno All is working now, backups are uploaded to the space. This is indeed due to compatibility reasons. Many s3-compatible endpoints use a different url templates compared to the default s3 url template. AWS S3 supports both styles, so by doing other object storage services can be used.

**Comment by xiano8494** [comment]
@nikksno S3 still shows as good during install

**Comment by nikksno** [comment]
Thanks to both of you

**Comment by HesselTjeerdsma** [comment]
@nikksno I just tested the latest version and everything is working fine!

**Comment by nikksno** [comment]
Perfect thanks to both!
