### ISSUE TITLE
After full reinstall backup doesn't run at all

### ISSUE THREAD

**Issue by xiano8494** [openspace42/raptor#17]
I wiped the installation by removing the openspace directory and then reinstalled using the -be flags.

I did also change the local backup location with the new install. Now backups won't run at all. The process starts, but then it seems to jump directly to testing the restore. I'm not sure if maybe I missed something whilst removing the previous install that is now interfering.

```
bash openspace42/raptor/tools/raptor-backup               

Starting raptor-backup script on 2018-04-15_10-13-26...

You have 0 local backups occupying 1 MB of space.

Now testing restore from S3 to /var/backups/raptor-backups/restores/s3/ to ensure existing backups integrity and passphrase match...

This is going to take some time. Please let the process run, it won't print any output until its done.

Testing restore from S3 failed.

This is likely due to an incorrect passphrase [check | /var/backups/raptor-backups/temp/duplicity-log | for messages like: | gpg: decryption failed: bad key |].

If this is the case, you've likely changed your backups encryption passphrase on this machine between your last backup and this one.

Aborting backup as proceeding would cause your S3 backups to be encrypted with two or more encryption keys at the same time.

This would render them unusable in the future should you ever need them.

Edit the file | /root/openspace42/raptor/conf/backups/s3/backups_passphrase | and set once again your previous encryption passphrase, then re-run this script.

If you have lost your previous encryption passphrase, delete all your S3 backups and re-run this script to make an entirely new backup set encrypted solely with the currently specified passphrase.

Exiting...
```

**Comment by nikksno** [comment]
That's not an issue with the re-install, it's actually expected behaviour with the feature we've introduced to optimize your issue brought up in https://github.com/openspace42/raptor/issues/14.

I've added a prompt on S3 test restore failure that allows you to proceed with a local-only backup anyway. Test it out with `-be`.

Thanks!

**Comment by nikksno** [comment]
I wiped the installation by removing the openspace directory

BTW @xiano8494 why did you wipe the dir? Just go have a clean install? Don't worry about that, every re-install ensures everything is clean, but that's the theory at least.

**Comment by xiano8494** [comment]
To clear all the configuration files in case that was causing my encryption issue.  Long shot, I know!

**Comment by nikksno** [comment]
Ok, yes absolutely, good idea, I'm pretty sure we've got that covered.
