### ISSUE TITLE
Add ability to reconfigure without running full setup

### ISSUE THREAD

**Issue by xiano8494** [openspace42/raptor#19]
It would be useful to be able to reconfigure without having to run the whole setup routine again. I know you can edit the files directly, but that is not user friendly and skips any validation. When you rerun setup most of the time is wasted simply watching it redownload etc.

**Comment by xiano8494** [comment]
If we did consider this, it might make sense to use the same configuration script at the beginning of the install script, and then run all the installs. In fact, even better, ask the questions about what to install all in one go, and then run the necessary.  That way we can answer questions and then leave it to finish, rather than having to keep checking to see what it is prompting for next.

**Comment by nikksno** [comment]
That would be cool, but we need to install dependencies before we're even able to ask such questions, and the logic is way to complex to be able to ask all questions in advance and then letting the install proceed on its own, as the logical causality is dependent on those dependencies, pun sort-of intended. Also, re-running the config before re-cloning is just one step shorter, and at that point it's better to re-clone and upgrade while you're at it. As the framework grows we might get to that ability, but I think it's not doable for now.

**Comment by nikksno** [comment]
Closing for now, I'll reopen it in the future on our bash-framework if it becomes feasible. Thanks for your suggestion.
