### ISSUE TITLE
bindfs depends on fuse

### ISSUE THREAD

**Issue by vasiler** [openspace42/raptor#21]
I have this error on Debian 8, when all is almost finished.

Setting up fuse (2.9.3-15+deb8u2) ...
Creating fuse device...
/run/udev or .udevdb or .udev presence implies active udev.  Aborting MAKEDEV invocation.
chmod: cannot access '/dev/fuse': No such file or directory
dpkg: error processing package fuse (--configure):
 subprocess installed post-installation script returned error exit status 1
dpkg: dependency problems prevent configuration of bindfs:
 bindfs depends on fuse; however:
  Package fuse is not configured yet.

dpkg: error processing package bindfs (--configure):
 dependency problems - leaving unconfigured
Processing triggers for libc-bin (2.19-18+deb8u10) ...
Errors were encountered while processing:
 fuse
 bindfs
E: Sub-process /usr/bin/dpkg returned an error code (1)

An error occured performing APT operations.

Exiting...

**Comment by vasiler** [comment]
Fixed:

mkdir /dev/fuse
chmod 777 /dev/fuse

apt-get install fuse

**Comment by nordurljosahvida** [comment]
@vasiler thanks for the input, are the `/dev/fuse` commands absolutely necessary in your experience? Does apt not figure that out on its own?

The fix I'd suggest is:

```
[raptor/functions line 804]

os-install_dependencies -p fuse bindfs
```
