### ISSUE TITLE
18.04 LTS install

### ISSUE THREAD

**Issue by HorseboxHeaven** [openspace42/raptor#22]
```
Enter hostname [fqdn]:hula.host
Adding repository for MySQL, please wait...
Adding repository for NGINX, please wait...
Adding repository for PHP, please wait...
Updating apt-cache, please wait...
Installing packages, please wait...
Oops Something went wrong!!
Check logs for reason `tail /var/log/ee/ee.log` & Try Again!!!

/root/openspace42/dna/functions/install_easyengine: line 38: cd: /var/www/22222/htdocs/db/pma: No such file or directory
root@ubuntu-s-2vcpu-2gb-sfo2-01:~#

```
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.1 LTS
Release:        18.04
Codename:       bionic

Fails on a brand new exclusive VPS and initial install with 18.04 LTS here Nick.

**Comment by nordurljosahvida** [comment]
@TerenceMilbourn sorry for the extremely late reply. I've now updated raptor for v4, only backup works for now. Let me know if you still have this issue.

**Comment by TerenceMilbourn** [comment]
I’ll check it out later today.

**Comment by nordurljosahvida** [comment]
Hi @HorseboxHeaven! I'm picking the project back up now and you should see all issues going away very soon, I'm finally completing the rewrite for the new version of the underlying framework and integrating new features. Let me know for any need. Closing for now.
