### ISSUE TITLE
Trying to update raptor

### ISSUE THREAD

**Issue by romapad** [openspace42/raptor#25]
By running command bash raptor/setup get this:
/root/raptor/functions: line 33: dna-define_vars: command not fount

**Comment by nordurljosahvida** [comment]
Hi again @romapad , sorry for the late replies. I've been keeping raptor on the back burner for some time now given that every EEv4 beta changed some behaviour, now the backup script is working, but I need to pull some newer code from synthia and dna to get raptor fully working once again. I'm also looking for someone who is interested in the restore part, as I haven't really had time to follow through with that.

I'll let you know as soon as I can look into it, that should be very soon.

**Comment by nordurljosahvida** [comment]
Hi @romapad! I'm picking the project back up now and you should see all issues going away very soon, I'm finally completing the rewrite for the new version of the underlying framework and integrating new features. Let me know for any need. Closing for now.
