### ISSUE TITLE
Installation error on ubuntu 16.04

### ISSUE THREAD

**Issue by Kyzoe** [openspace42/raptor#26]
After following the commands like stated in the readme, i get the following error when i want to execute the command: bash raptor/setup

Initiating setup...
/root/raptor/functions: line 181: /root/openspace42/dna/functions/*: No such file or directory

please guide me on this error.

**Comment by nordurljosahvida** [comment]
@Kyzoe raptor is currently under full redevelopment and will be unusable for a little. Watch the project to be notified when it'll be back!
