### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by zietbukuel** [openspace42/raptor#27]
root@cloud:~# bash raptor/setup
Initiating setup...

/root/raptor/functions: line 184: /root/openspace42/dna/functions/*: No such file or directory

Using Ubuntu 18.04

**Comment by nordurljosahvida** [comment]
Hi @zietbukuel , raptor is currently under redevelopement, a new release ready for easyengine v4 should be out after the summer, in the mean time you could try installing via `bash raptor/setup -d "v0.3.14" -pb` but it's anyone's guess if that will work.

**Comment by gtu-myowin** [comment]
> but it's anyone's guess if that will work.

Hi @nordurljosahvida, by any chance the script has been updated yet because this is not working for me. I got the following message

    Initiating setup...

    Invalid content for | custom_dna_version | in function | main |.

    Exiting...

**Comment by nordurljosahvida** [comment]
Hi @gtu-myowin! I'm picking the project back up now and you should see all issues going away very soon, I'm finally completing the rewrite for the new version of the underlying framework and integrating new features. Let me know for any need. Closing for now.
