### ISSUE TITLE
Unable to set local backup storage location

### ISSUE THREAD

**Issue by xiano8494** [openspace42/raptor#4]
I can't see how I would set a different local storage location.
Several of the sites to backup are very large, meaning the backup size is much larger than the available disk space. 

Ideally, I wouldn't store any backups locally, but I assume the script requires local storage to create the backups before pushing off to S3.

I would, therefore, like to set an alternative local storage location so that I can complete backups. Whilst I imagine I could do it by hacking the script, I think it would make sense to be able to set this during setup?

**Comment by nikksno** [comment]
Very good point. I'd love for the backup to be able to occur to S3 without any local archiving being performed first, but that would break the way duplicity works, so local archiving is the way to go. Let me check for ways to archive things elsewhere. What location are you looking to use?

**Comment by nikksno** [comment]
Working on it. Will be ready by tomorrow.

**Comment by xiano8494** [comment]
I don't mind massively, just so long as it is unique to Raptor so I can add mount point there.  For it to be configurable would be ideal. It would also need to use somewhere other than /tmp for the temp files too, otherwise we may hit the same problem.  Maybe /var/backup/ ?

**Comment by nikksno** [comment]
It will be configurable. I've successfully moved the temp dir inside the backup dir, so that's also figured out. Testing out the latest commit now, will update you shortly.

**Comment by nikksno** [comment]
Ok, just published a few fixes. If you've already tried try in the last hour please try again now. Thanks.

**Comment by nikksno** [comment]
@xiano8494 published new version. You can install without `-be` as normal and you will get the latest updates. I've been running backups on /var/raptor/ on our openspace server for 2 days now and everything seems consistently good. Let me know!

**Comment by xiano8494** [comment]
I'm afraid there is still an issue, it would appear that the script still checks the OS disks available space, so although I have a large disk attached and have set the backup location to this disk, I still get a warning:

Starting raptor-backup script on 2018-04-08_11-52-06...
You have 0 local backups occupying 1 MB of space.
Estimated backup size [170499 MB] LARGER than available disk space [20067 MB].

**Comment by nikksno** [comment]
That's a lot of sites! ;]
Should be fixed in latest commit. Try installing the latest beta please.
Thanks!

**Comment by nikksno** [comment]
It occurs to me that I also have to change the directory where restores are stored to avoid occupying that same space when backing up to S3 [as a test restore] or when actually performing a restore. Are you backing up to S3?

**Comment by nikksno** [comment]
@xiano8494 fixed that too, restore-time temp data is now stored inside the backups directory too, something I thought would break a bunch of stuff but no issues for now, but then again even with both a production server and a test server I can't try out every possible combination of things on every commit, please try re-installing with beta mode on and let me know if everything works and please monitor the `/root/openspace42/raptor` directory to ensure no "backups" or "restores" dirs are created and make sure that all dirs [archive, latest, restores, temp] are actually created on your external location. Also, if you'd like to share if you're using S3 that would help me understand what kinds of tests you're performing on your machine. Thanks for the help!

**Comment by nikksno** [comment]
Also just tried every possible combination on both servers and everything seems to work both with default *and* custom location, but the custom location is just `/var/raptor` and not an external disk, although it shouldn't matter. Hope we're good to go!

**Comment by xiano8494** [comment]
And, as a side note, not a lot of sites, just big sites! Photography blogs, large amounts of high-resolution imagery! :)

**Comment by nikksno** [comment]
@xiano8494 awesome! I'm happy someone is using raptor! If you know anyone please spread the word so that we can have several people beta testing and making sure our framework is always up to date and can serve other projects as well!

**Comment by nikksno** [comment]
I'll close the issue for now, feel free to re-open with any issues. Thanks!
