### ISSUE TITLE
Pwgen missing causes strange behaviours

### ISSUE THREAD

**Issue by xiano8494** [openspace42/raptor#8]
Inititally the script will crash during S3 config due to missing Pwgen.  Installing pwgen and restarting the script results in encryption phrase being blank.  I assume that although pwgen is missing the script has already created the config file for the passphrase and then leaves it blank.

**Comment by nikksno** [comment]
A byproduct of the same issue introduced the other day - see your other issue for updates here: https://github.com/openspace42/raptor/issues/6. Fix is in the next commit.
