### ISSUE TITLE
Unable to download file, /tmp/eeupdate20180407-125625

### ISSUE THREAD

**Issue by HesselTjeerdsma** [openspace42/raptor#9]
When I try to install raptor using the install instructions my installation terminates and gives the following error: 

Now [re-]installing and updating EasyEngine...
Executing apt-get update, please wait...
[ Sat Apr  7 12:56:25 CEST 2018 ] You already have EasyEngine 3.7.5, exit status =  1
Downloading update script        Unable to download file, /tmp/eeupdate20180407-125625

Could you please help me fix this?

**Comment by nikksno** [comment]
It's an issue with EE but I've implemented a way around this in response to another ticket from the other day, I still haven't pushed a stable version of raptor with this workaround, please run the installer in bleeding-edge mode with `bash raptor/setup -be` and let me know if it works for you. Thanks!

**Comment by nikksno** [comment]
@HesselTjeerdsma published new version. You can install without -be as normal and you will get the latest updates from the stable version. Let me know!

**Comment by HesselTjeerdsma** [comment]
@nikksno Thanks for fixing it! All is working fine now

**Comment by nikksno** [comment]
Great thank you
